#!/usr/bin/env bash

directory_path=$(zoxide query -l | fzf)

# if empty, exit
if [ -z "$directory_path" ]; then
    exit 0
fi

directory_name=$(basename "$directory_path" | tr . _)

if ! tmux has-session -t "$directory_name" 2> /dev/null; then
    tmux new-session -s "$directory_name" -c "$directory_path" -d
fi

if [ -z "$TMUX" ]; then
    tmux attach -t "$directory_name"
else
    tmux switch-client -t "$directory_name"
fi
