---
- name: "Check if the SSH key exists for {{ item.type }}"
  ansible.builtin.stat:
    path: "~/.ssh/keys/{{ item.key_filename }}"
  register: ssh_key

- name: "Get the passphrase for key to be generated for {{ item.type }}"
  ansible.builtin.pause:
    prompt: "Enter the SSH passphrase for the {{ item.type }} key"
    echo: false
  when: not ssh_key.stat.exists
  register: ssh_passphrase

- name: "Generate the SSH key for {{ item.type }}"
  when: not ssh_key.stat.exists
  # NOTE: the user module doesn't have an option to set iterations (e.g. -a 100)
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: ".ssh/keys/{{ item.key_filename }}"
    ssh_key_passphrase: "{{ ssh_passphrase.user_input }}"
    force: false
  register: key_gen

- name: Add the fingerprint to a temp file to check for it in later runs
  when: (key_gen.changed) and (not key_gen.failed)
  ansible.builtin.copy:
    content: "{{ key_gen.ssh_fingerprint }}"
    dest: "../../.tmp/{{ item.key_filename }}-fingerprint"
    mode: "0600"

  # NOTE: the fingerprint file has to be present
- name: Check if the key was added to the ssh-agent
  ansible.builtin.set_fact:
    key_loaded: >-
      {{ lookup('file', '../../.tmp/' + item.key_filename + '-fingerprint') in lookup('pipe', 'ssh-add -l') }}

- name: Add the key to the ssh-agent and store the passphrase in keychain (macOS)
  when: ansible_system == "Darwin" and (((key_gen.changed) and (not key_gen.failed)) or (not key_loaded))
  changed_when: ((key_gen.changed) and (not key_gen.failed)) or (not key_loaded)
  ansible.builtin.command:
    cmd: "ssh-add --apple-use-keychain ~/.ssh/keys/{{ item.key_filename }}"

- name: Add the key to the ssh-agent (Linux)
  when: ansible_system == "Linux" and (((key_gen.changed) and (not key_gen.failed)) or (not key_loaded))
  changed_when: ((key_gen.changed) and (not key_gen.failed)) or (not key_loaded)
  ansible.builtin.command:
    # TODO: is this going to cause an interactive prompt for the passphrase?
    # and if so, can we pipe it from the passphrase variable we gathered earlier?
    cmd: "ssh-add ~/.ssh/keys/{{ item.key_filename }}"
# TODO: add a task to edit ~/.ssh/config file and add relevant sections if they don't exist
# e.g., use the block in file or line in file modules to check that all hosts have their keys
# added to the agent and only identities are allowed. Also add a previous task to check for
# the existence of the config file and create it if not.
# Using home-manager is another idea/consideration.
